.\"
.ig
Copyright (C) 2012-2018 Pierre Jean Fichet
<pierrejean dot fichet at posteo dot net>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
..
.\" DA Pierre-Jean Fichet
.\" DS Utroff utmac manual
.\" DT Utroff utmac manual
.\" DK utroff utmac u-ref troff
.
.
.
.TH UTMAC 7 2018-04-24
.
.
.
.SH NAME
.PP
\fButmac\fR: A troff macro set
.
.
.
.SH DESCRIPTION
.PP
The \fIU troff macros\fR — \fIutmac\fR — is a set of \fItroff\fR
macros aiming to produce beautiful documents easily. Bibliography,
indexes, table of content and summaries can be automatically inserted.
\fIUtmac\fR informs about orphans, widows and empty lines at the
bottom of page. \fIUtmac\fR can produce pdf files, ReStructuredText
files, plain text file, and clean xml files — and so, with some xsl
stylesheet, flat open document texts (fodt) and html files.
.PP
\fIUtmac\fR is made to be used with \fBneatroff\fR to produce
postscript and pdf files. To produce plain text files, manual pages,
and xml files, \fBgroff -k -Tutf8 -M@MACDIR@\fR can be used instead.
.
.
.
.SH FILES
.
.
.
.SS User macro files
.RS 3
.PP
The following macro files can be used by the user (called
with the \fB-m\fR option of troff):
.TP
\&\fIuh\fR
Made with humanities in mind. It use marginal notes instead
of footnotes.
.TP
\&\fIul\fR
A macro to write letters and short texts.
.TP
\&\fIum\fR
Translate a \fIutmac\fR document to manpage with \fInroff\fR.
.TP
\&\fIut\fR
Translate an \fIutmac\fR document to a flat text file (such as
README files) with \fInroff\fR.
.TP
\&\fIus\fR
Made for technical documentation. It uses a common
layout, reminiscent of the old troff \fIms\fR.
.TP
\&\fIuw\fR
Translate an \fIutmac\fR document to the markdown wiki format.
.TP
\&\fIux\fR
Translate an \fIutmac\fR document to xml. This macro must be
used with the
postxml(1)
post-processor.
.PP
Additionnaly, some configuration can be achieved by loading the
following macros:
.TP
\&\fIu-en\fR
English localization (default).
.TP
\&\fIu-fr\fR
French localization.
.TP
\&\fIu-apolline\fR
Use the Porchez Typofonderie Apolline font.
.TP
\&\fIu-libertine\fR
Use the linux libertine font.
.TP
\&\fIu-biolinum\fR
Use the linux biolinum font.
.TP
\&\fIu-biollib\fR
Use a mix of Linux Libertine and Biolinum.
.
.
.
.SH MACROS
.PP
An \fIutmac\fR document should be structured in four parts:
metadatas, definition of some register, content, and appendix. The
content can contain header macros, summary macros, paragraph
macros, typographic macros, note macros, include macros, links
macros, keywords macros.
.PP
All macros have two letters; the first one define the gender of the
macro: meta\fBD\fRatas, \fBR\fRegister, \fBH\fReading, \fBS\fRummary,
\fBP\fRaragraph, \fBT\fRypographic, \fBN\fRotes, \fBI\fRnclude,
\fBL\fRinks, \fBK\fReywords, Appendi\fBX\fR.
.
.
.
.SS Metadata macros
.RS 3
.PP
These macro are used to populate the metadatas of the final
file (pdf, xml, or html). They must be inserted in the
first page of the document — their natural place being the
first lines of the file.
.TP
\&\fBDA\fR \fIauthor name\fR
Define author metadata.
.TP
\&\fBDI\fR \fIIdentifier\fR
Define identifier (RCS Id...).
.TP
\&\fBDK\fR \fIlist of keywords\fR
Define keywords metadata.
.TP
\&\fBDS\fR \fIsubject of the text\fR
Define subject metadata.
.TP
\&\fBDT\fR \fItitle of the text\fR
Define title metadata.
.
.
.
.SS Register macros to define format and layout
.RS 3
.PP
Some number register are used by \fIutmac\fR to make or not
some actions. Set to 1, the action is done, set to 0, the
action is not done. The following macro can be used to
define the state of this number register. The name of the
macro is also the name of the number register. For example,
\fB.RV 1\fR acts like \fB.nr RV 1\fR. This is usefull to
format a document from the command line:
.PP
.EX
troff -rRV=1 -muh file
.EE
.TP
\&\fBRV\fR \fInum\fR
If \fInum\fR=1, use a recto-verso layout.
Default is 0.
.TP
\&\fBRI\fR \fInum\fR
If \fInum\fR=1, replace references by \fIIdem\fR when
needed.
Default is 1.
.TP
\&\fBRH\fR \fInum\fR
If \fInum\fR=1, print help message.
Help message inform about orphans, widows, blank at the
bottom of pages, note diverted to next page, and multiple
definition of anchor keyword.
Default is 1.
.TP
\&\fBRL\fR [\fIfr\fR|\fIen\fR]
Set language of file. Use this macro to localize some string
and to respect local typographic standard if you want to
override the default which should be defined by the macro in
the \fBUTMAC\fR environment variable.
.TP
\&\fBRO\fR \fInum\fR
If \fInum\fR=1, replace some part of a reference (issuer,
city and date) by \fIop. cit.\fR if the same reference has
appeared in the text.
Default is 1.
.TP
\&\fBRP\fR \fInum\fR
If \fInum\fR=1, print page number.
Default is 1.
.TP
\&\fBRN\fR \fInum\fR
If \fInum\fR=1, print reference in a note, if \fInum\fR=0,
the reference is printed directly in the text, by using the
\fBPQ\fR macro.
Default is 1.

.
.
.
.SS Heading macros
.RS 3
.PP
These macro are used to print headings and to record them
for a summary or a table of contents.
.TP
\&\fBH1\fR \fITitle of the book\fR
Book heading.
.TP
\&\fBH2\fR \fITitle of the chapter\fR
Chapter heading.
.TP
\&\fBH3\fR \fITitle of the paragraph\fR
Paragraph heading.
.TP
\&\fBH4\fR \fISubheading\fR
Subheading.
.TP
\&\fBH0\fR \fITemporary title\fR
Temporary heading, printed in the header or in the footer of
the current page. This heading is not recorded in the table
of content.
.TP
\&\fBH*\fR \fIMargin title\fR
Heading printed in header or footer of the following pages,
and in the current ones if H0 is not set for this page. This
heading is not recorded in the table of content.
.
.
.
.SS Summaries macros
.RS 3
.PP
To print a summary, two or three pass of troff are needed:
the first one to record the summary, the second one to print
it, and a third one might be necessary to adjust the page
number if the summary is longer than one page.
.TP
\&\fBS2\fR
Print a summary of chapter headings. The summary is printed
on a new page.
.TP
\&\fBS3\fR
Print a summary of paragraph headings. The summary is
printed on the actual page.
.TP
\&\fBS4\fR
Print a summary of subheading. The summary is printed on the
actual page.
.TP
\&\fBS*\fR
Print the whole table of content as a summary.
.
.
.
.SS Paragraph macros
.RS 3
.TP
\&\fBPB\fR
Left indent (extended) pargraph. Usefull to \fBb\fRegin some
sort of lists.
.TP
\&\fBPC\fR
Centered paragraph.
.TP
\&\fBPP\fR
Justified paragraph.
.TP
\&\fBPQ\fR
Quote paragraph.
.TP
\&\fBPI\fR [\fIbullet\fR]
List paragraph. Default bullet is usually an emdash
(\fI\e(em\fR).
.TP
\&\fBPL\fR
Left align paragraph.
.TP
\&\fBPR\fR
Right align paragraph.
.TP
\&\fBPX\fR
Example paragraph. Text is not filled.
.
.
.
.SS Note macros
.RS 3
.TP
\&\fBNS\fR \fIno\fR
Start a numbered note.
The default is to print a number before the
note, but if an argument is given, no number will be
printed. To insert a number reference to the note in the
text, use the \fB*\fR string, say insert: \fB\e**\fR where
you want the number to appear.
.TP
\&\fBNT\fR
Print a note on top of the others, or in the flow of the
text, depending of the macro used.
.TP
\&\fBNB\fR
Print a note in the bottom of the page, or in the flow of
the text, depending of the macro used.
.TP
\&\fBNE\fR
End \fINS\fR, \fINT\fR or \fINB\fR.
.
.
.
.SS Include macros
.RS 3
.PP
These macros are used to include an encapsulated postscript document
or a pdf one. These documents are often images, which can be produced
with the \fBconvert\fR command from \fBImageMagick\fR for \fIeps\fR
files and \fBps2pdf\fR for \fIpdf\fR files:
.PP
.EX
convert image.jpg image.eps
ps2pdf -dEPSCrop image.eps image.pdf
.EE
.TP
\&\fBEPS\fR \fIfile.eps\fR [\fIl\fR|\fIc\fR|\fIr\fR|\fIindent\fR] [\fIwidth\fR] [\fIheight\fR]
Include an \fIeps\fR file.
.TP
\&\fBPDF\fR \fIfile.pdf\fR [\fIl\fR|\fIc\fR|\fIr\fR|\fIindent\fR] [\fIwidth\fR] [\fIheight\fR]
Include a \fIpdf\fR file.
.
.
.
.SS Link macros
.RS 3
.PP
Link macros are used to insert links in a document. If a link macro
is preceded by the \fBLT\fR macro it will use the arguments of
\fBLT\fR as a replacement text for the link. Otherwise, the link is
printed.
.PP
.EX
This will print the url followed by a dot:
\fB.\fR\fBLU\fR http://utroff.org .
While this will print «link» followed by a dot:
\fB.\fR\fBLT\fR link ». «
\fB.\fR\fBLU\fR http://utroff.org
.EE
.TP
\&\fBLK\fR \fIkeyword\fR
Insert an anchor named \fIkeyword\fR for internal links. Does not
print anything.
.TP
\&\fBLL\fR \fIkeyword stringafter stringbefore\fR
Insert a link to the anchor \fIkeyword\fR. The text to link is defined
by the \fBLT\fR macro — if it is not defined, the url is printed,
surrounded by \fIstringbefore\fR and \fIstringafter\fR.
.TP
\&\fBLM\fR \fIemail stringafter stringbefore\fR
Insert a link to an email address. The text to link is defined by the
\fBLT\fR macro — if it is not defined, the url is printed,
surrounded by \fIstringbefore\fR and \fIstringafter\fR.
.TP
\&\fBLT\fR \fItext stringafter stringbefore\fR
Define \fItext\fR as the replacement text for the following link. It
is printed surrounded by \fIstringbefore\fR and \fIstringafter\fR.
.TP
\&\fBLU\fR \fIurl stringafter stringbefore\fR
Insert a link to an url. The text to link is defined by the \fBLT\fR
macro — if it is not defined, the url is printed, surrounded by
\fIstringbefore\fR and \fIstringafter\fR.
.
.
.
.SS Keyword macros
.RS 3
.PP
Keyword macros add semantic information to the source and the
final document and index them. They do not print anything.
The following keyword macros are defined:
.TP
\&\fBKA\fR \fIacronym\fR
Index an acronym.
.TP
\&\fBKN\fR \fIname\fR
Index a name.
.TP
\&\fBKO\fR \fIobject\fR
Index an object.
.TP
\&\fBKT\fR \fItitle\fR
Index the title of a book (references are automatically indexed using
it).
.TP
\&\fBKW\fR \fIword\fR
Index a word.
.
.
.
.SS Appendix macros
.RS 3
.TP
\&\fBXB\fR [\fIbibliography\fR]
Print a bibliography. If \fIbibliography\fR is omitted,
\fIUtmac\fR
will use the \fI$REFER\fR environment variable. The bibliography
begins with the \fBH3\fR macro. \fIUtmac\fR try to sort the
bibliography using \fIurefer\fR \fB-i\fR option, but this
doesn't give correct result on some bibliography
list. For a perfect result, you should sort your
bibliography with \fIsortbib\fR. See \fBu-ref\fR(7).
.TP
\&\fBXI\fR
Print the existing indexes. To index something, use an keyword macro. Each index begin with the \fBH3\fR macro.
.TP
\&\fBXT\fR
Print a table of content. The table begin with the \fBH3\fR
macro.
.
.
.
.SH FONTS
.PP
In \fIutmac\fR, fonts are defined by a single uppercase
letter string. As in the xml style, these strings must
enclose the text and can be embedded:
.PP
.EX
Roman \fB\e*I\fRitalic, \fB\e*B\fRbolditalic\fB\e*B\fR\fB\e*I\fR, roman.
.EE
.PP
So, in an \fIutmac\fR document, you must avoid the raw troff
\fB\ef\fR and \fB.fp\fR commands.
.PP
Font strings are defined as follow:
.TP
\&\fBB\fR
Bold font.
.TP
\&\fBI\fR
Italic font.
.TP
\&\fBC\fR
Small Capital font.
.TP
\&\fBA\fR
Acronym font (capital to small capital).
.TP
\&\fBU\fR
Superscript font (upper).
.TP
\&\fBL\fR
Dowscript font (lower).
.TP
\&\fBF\fR
Final font (glyphs that might only appear at the end of a
line).
.TP
\&\fBM\fR
Monospace font.
.
.
.
.SH EXAMPLE
.PP
The following example is a fully commented simple \fIutmac\fR
document. As a summary is inserted, two pass of \fItroff\fR
are needed. If the summary is longer than one page, a third
pass of troff would be needed to handle correctly the page
references, but this is not the case in this short example.
So, this document can be build using these commands:
.PP
.EX
troff -muh alice.tr \fB>\fR /dev/null
troff -muh alice.tr \fB|\fR dpost \fB|\fR ps2pdf - alice.pdf
.EE
.PP
.EX
\fB.\fR\fI\e" Start example\fR
\fB.\fR\fI\e" Use recto verso\fR
\fB.\fR\fBRV\fR
\fB.\fR\fI\e" Define metadatas\fR
\fB.\fR\fBDA\fR Lewis Carroll
\fB.\fR\fBDT\fR Alice's adventures in wonderland and Through the looking glass
\fB.\fR\fBDK\fR alice nabuchodonosor jabberwocky
\fB.\fR\fI\e" Build first page\fR
\fB.\fR\fBH0\fR Lewis Carroll
\fB.\fR\fBH1\fR Alice's adventures
\fB.\fR\fI\e" Insert a summary of chapter headings\fR
\fB.\fR\fBS2\fR
\fB.\fR\fI\e" First chapter heading\fR
\fB.\fR\fBH2\fR Alice's adventures in wonderland
\fB.\fR\fI\e" A short exergue\fR
\fB.\fR\fBNT\fR
All in the golden afternoon
Full leisurly we glide
\fB.\fR\fBNE\fR
\fB.\fR\fI\e" First paragraph\fR
\fB.\fR\fBH3\fR Down the rabbitt hole
\fB.\fR\fI\e" Some text with font definitions, and a note appeal\fR
\fB.\fR\fBPP\fR
\fB\e*C\fRAlice\fB\e*C\fR was beginning to be very tired of sitting by her
sister on the bank, and of having nothing to do: once or
twice she had peeped into the book her sister was reading,
but it had no pictures or conversations in it, "\fB\e*I\fRand what
is the use of a book\fB\e*I\fR" thought \fB\e*C\fRAlice\fB\e*C\fR, "\fB\e*I\fRwithout
pictures or conversations?\fB\e*I\fR\fB\e**\fR"
\fB.\fR\fI\e" A note\fR
\fB.\fR\fBNS\fR
Yes, what is the use of such a book?
\fB.\fR\fBNE\fR
\fB.\fR\fI\e" Some other chapters and paragraphs...\fR
\fB.\fR\fBH3\fR The pool of tears
\fB.\fR\fBH2\fR Through the looking glass
\fB.\fR\fI\e" Table of content\fR
\fB.\fR\fBXT\fR
\fB.\fR\fI\e" Stop example\fR
.EE
.
.
.
.SH SEE ALSO
.PP
utmac-hack(7),
u-ref(7),
postxml(1),
idx(1),
refer(1).
.
.
.
.SH LICENSE
.PP
\fIUtmac\fR macros and this manual page are distributed under
the
isc license.
.
.
.
.SH AUTHOR
.PP
Pierre-Jean Fichet.
